FROM kong:3.7.1-ubuntu

USER root
RUN mkdir -p /usr/local/share/lua/5.1/kong/plugins/argus-redact-bridge

COPY kong/plugins/argus-redact-bridge/ /usr/local/share/lua/5.1/kong/plugins/argus-redact-bridge/

USER kong
